spring:
  application:
    name: around-the-horn
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pxukqohrckdfo4ty.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/zi5eh7bpvj5vpih0?autoReconnect=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      max-lifetime: 30000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.

twilio:
  account-sid: ${twilio.account.sid}
  api:
    sid: ${twilio.api.sid}
    secret: ${twilio.api.secret}
