spring:
  application:
    name: around-the-horn
  output:
    ansi:
      enabled: ALWAYS

twilio:
  room-name: ath
  account-sid: ${twilio.account.sid}
  api:
    sid: ${twilio.api.sid}
    secret: ${twilio.api.secret}
